const launchForm=document.querySelector('#launch-form');
if(launchForm){
  const steps=[...launchForm.querySelectorAll('.launch-step')],nextButton=launchForm.querySelector('#form-next'),backButton=launchForm.querySelector('#form-back'),submitButton=launchForm.querySelector('#form-submit'),currentStepLabel=launchForm.querySelector('#current-step'),progressFill=launchForm.querySelector('#progress-fill'),status=launchForm.querySelector('.launch-status');
  let activeStep=0;
  const showStep=index=>{activeStep=index;steps.forEach((step,i)=>step.classList.toggle('active',i===index));currentStepLabel.textContent=String(index+1);progressFill.style.width=`${(index+1)/steps.length*100}%`;backButton.hidden=index===0;nextButton.hidden=index===steps.length-1;submitButton.hidden=index!==steps.length-1;status.textContent='';steps[index].querySelector('legend')?.focus?.()};
  const validateStep=()=>{const required=[...steps[activeStep].querySelectorAll('[required]')];const invalid=required.find(field=>field.type==='radio'?!launchForm.querySelector(`[name="${field.name}"]:checked`):!field.checkValidity());if(invalid){status.textContent=invalid.type==='radio'?'Выберите один из вариантов.':'Заполните обязательное поле.';invalid.focus();return false}return true};
  nextButton.addEventListener('click',()=>{if(validateStep())showStep(Math.min(activeStep+1,steps.length-1))});
  backButton.addEventListener('click',()=>showStep(Math.max(activeStep-1,0)));
  document.querySelectorAll('[data-route-choice]').forEach(link=>link.addEventListener('click',()=>{const radio=launchForm.querySelector(`[name="stage"][value="${link.dataset.routeChoice}"]`);if(radio){radio.checked=true;showStep(0)}}));
  launchForm.addEventListener('submit',event=>{event.preventDefault();if(!validateStep())return;const data=new FormData(launchForm),support=data.getAll('support').join(', ')||'не указано',lines=['Новая заявка на запуск продукта FGN','','Этап: '+data.get('stage'),'Продукт: '+data.get('product'),'Партия: '+(data.get('volume')||'не указана'),'Состав / назначение: '+(data.get('composition')||'не указано'),'Сырьё: '+data.get('material'),'Нужна помощь: '+support,'','Имя: '+data.get('name'),'Компания: '+(data.get('company')||'не указана'),'Телефон: '+data.get('phone'),'E-mail: '+(data.get('email')||'не указан'),'Предпочтительный контакт: '+data.get('contact_method'),'Комментарий: '+(data.get('comment')||'нет')];status.textContent='Заявка сформирована. Открываем почтовую программу…';window.location.href='mailto:Burunduk.shop@mail.ru?subject='+encodeURIComponent('Запуск продукта FGN — '+data.get('name'))+'&body='+encodeURIComponent(lines.join('\n'))});
  showStep(0);
}
